<?php

declare(strict_types=1);

return [
    "actions" => [
        ["code" => "view", "label" => "Ver", "description" => "Consultar pantallas, listados y detalles."],
        ["code" => "create", "label" => "Crear", "description" => "Registrar nuevos datos."],
        ["code" => "update", "label" => "Editar", "description" => "Modificar datos existentes."],
        ["code" => "delete", "label" => "Eliminar", "description" => "Eliminar registros cuando el módulo lo permita."],
        ["code" => "export", "label" => "Exportar", "description" => "Descargar reportes o archivos."],
        ["code" => "import", "label" => "Importar", "description" => "Realizar cargas masivas."],
        ["code" => "operate", "label" => "Operar", "description" => "Ejecutar procesos como ventas, movimientos, cierres o traslados."],
    ],

    "route_tokens" => [
        "export" => ["export", "download", "template"],
        "import" => ["import", "upload"],
        "delete" => ["destroy", "delete"],
        "operate" => [
            "pos", "cancel", "open", "close", "movement", "movements",
            "operation", "operations", "transfer", "transfers", "receive",
            "assign", "unassign", "qrcamera", "qrscanner", "finalize",
        ],
        "create" => ["create", "store"],
        "update" => ["edit", "update"],
    ],

    "route_actions" => [
        "stocks_management.guides.store" => "operate",
        "user_attendances.checkin" => "operate",
        "user_attendances.biometric-checkin" => "operate",
        "user_attendances.checkout" => "operate",
        "user_attendances.breaks.start" => "operate",
        "user_attendances.breaks.end" => "operate",
        "user_attendances.corrections.store" => "update",
        "user_attendances.corrections.review" => "update",
        "user_attendances.export" => "export",
        "roles.duplicate" => "create",
        "tracking_subscriptions.renew" => "create",
        "tracking_notifications.retry" => "operate",
        "tracking_attendances.corrections.store" => "update",
        "tracking_attendances.corrections.review" => "update",
        "tracking_attendances.export" => "export",
        "recipes.waste-records.store" => "operate",
        "purchases.returns.store" => "operate",
        "purchases.approve" => "operate",
        "assets.categories.store" => "create",
        "assets.categories.update" => "update",
        "users.biometric-fingerprints.store" => "update",
        "biometric_devices.credentials.rotate" => "update",
        "users.password.update" => "update",
        "users.authentication-events" => "view",
        "reports.sale" => "export",
        "reports.customers" => "export",
        "reports.items" => "export",
        "reports.branches" => "export",
        "reports.sales" => "export",
        "reports.users" => "export",
        "reports.settlements" => "view",
        "master_data.store" => "create",
        "master_data.update" => "update",
        "branches.series.audit.export" => "export",
        "branches.public-attendance-link" => "view",
        "book_complaints.attachments.download" => "view",
        "service_operations.sessions.store" => "operate",
        "service_operations.floors.store" => "create",
        "service_operations.stations.layout" => "update",
        "service_operations.items.store" => "operate",
        "service_operations.sessions.start" => "operate",
        "service_operations.sessions.complete" => "operate",
        "service_operations.sessions.reassign" => "operate",
        "service_operations.sessions.pause" => "operate",
        "service_operations.sessions.resume" => "operate",
        "service_operations.sessions.cancel" => "operate",
        "service_operations.items.start" => "operate",
        "service_operations.items.complete" => "operate",
        "service_operations.items.preparation-status" => "operate",
        "sales.deliveries.deliver" => "operate",
    ],

    /* Endpoints compartidos por varias pantallas del mismo módulo técnico. */
    "route_modules" => [
        "master_data.list" => ["companies.index"],
        "master_data.store" => ["companies.index"],
        "master_data.update" => ["companies.index"],
        "branches.series.audit" => ["branches.index"],
        "branches.series.audit.export" => ["branches.index"],
        "assets.categories.list" => ["assets.index"],
        "assets.categories.store" => ["assets.index"],
        "assets.categories.update" => ["assets.index"],
        "sales.initParams" => ["sales.index", "sales.create", "sales.deliveries.index", "sales.pos"],
        "sales.options" => ["sales.create"],
        "sales.customerOptions" => ["sales.index", "sales.deliveries.index"],
        "sales.list" => ["sales.index"],
        "sales.cancel" => ["sales.index"],
        "sales.store" => ["sales.create", "sales.pos"],
        "sales.deliveries" => ["sales.deliveries.index"],
        "sales.deliveries.deliver" => ["sales.deliveries.index"],
        "quotations.options" => ["quotations.create"],

        "user_attendances.initParams" => ["user_attendances.index"],
        "user_attendances.list" => ["user_attendances.index"],
        "user_attendances.weekly" => ["user_attendances.index"],
        "user_attendances.export" => ["user_attendances.index"],
        "user_attendances.checkin" => ["user_attendances.index"],
        "user_attendances.biometric-checkin" => ["user_attendances.index"],
        "user_attendances.checkout" => ["user_attendances.index"],
        "user_attendances.breaks.start" => ["user_attendances.index"],
        "user_attendances.breaks.end" => ["user_attendances.index"],
        "user_attendances.corrections.store" => ["user_attendances.index"],
        "user_attendances.corrections.review" => ["user_attendances.index"],

        "users.biometric-fingerprints.store" => ["users.index"],

        "service_operations.initParams" => ["restaurant_pos.index", "service_sessions.index"],
        "service_operations.board" => ["restaurant_pos.index"],
        "service_operations.options" => ["restaurant_pos.index", "service_sessions.index"],
        "service_operations.floors" => ["restaurant_pos.index"],
        "service_operations.floors.store" => ["restaurant_pos.index"],
        "service_operations.stations" => ["restaurant_pos.index", "service_sessions.index"],
        "service_operations.stations.store" => ["restaurant_pos.index", "service_sessions.index"],
        "service_operations.stations.layout" => ["restaurant_pos.index"],
        "service_operations.sessions" => ["restaurant_pos.index", "service_sessions.index"],
        "service_operations.sessions.store" => ["restaurant_pos.index", "service_sessions.index"],
        "service_operations.sessions.show" => ["restaurant_pos.index", "service_sessions.index"],
        "service_operations.items.store" => ["restaurant_pos.index", "service_sessions.index"],
        "service_operations.sessions.start" => ["restaurant_pos.index", "service_sessions.index"],
        "service_operations.sessions.complete" => ["restaurant_pos.index", "service_sessions.index"],
        "service_operations.sessions.reassign" => ["restaurant_pos.index", "service_sessions.index"],
        "service_operations.sessions.pause" => ["restaurant_pos.index", "service_sessions.index"],
        "service_operations.sessions.resume" => ["restaurant_pos.index", "service_sessions.index"],
        "service_operations.sessions.cancel" => ["restaurant_pos.index", "service_sessions.index"],
        "service_operations.items.start" => ["restaurant_pos.index", "service_sessions.index"],
        "service_operations.items.complete" => ["restaurant_pos.index", "service_sessions.index"],
        "service_operations.items.preparation-status" => ["restaurant_pos.index"],

        "stocks_management.index" => ["stocks_management.stock.index"],
        "stocks_management.initParams" => [
            "stocks_management.stock.index",
            "stocks_management.kardex.index",
            "stocks_management.transfers.index",
            "stocks_management.valued.index",
        ],
        "stocks_management.list" => ["stocks_management.stock.index"],
        "stocks_management.movements" => [
            "stocks_management.kardex.index",
            "stocks_management.transfers.index",
            "stocks_management.valued.index",
        ],
        "stocks_management.alerts" => ["stocks_management.stock.index"],
        "stocks_management.guides" => ["stocks_management.stock.index"],
        "stocks_management.guides.store" => ["stocks_management.stock.index"],
        "stocks_management.movements.store" => ["stocks_management.stock.index"],
        "stocks_management.operations.store" => ["stocks_management.stock.index"],
        "stocks_management.transfers.store" => ["stocks_management.transfers.index"],
        "stocks_management.export" => [
            "stocks_management.stock.index",
            "stocks_management.kardex.index",
            "stocks_management.transfers.index",
            "stocks_management.valued.index",
        ],

        "cash_registers.index" => ["cash_registers.index"],
        "cash_registers.initParams" => [
            "cash_registers.index",
            "cash_sessions.index",
            "cash_movements.index",
            "cash_summary.index",
        ],
        "cash_registers.list" => ["cash_registers.index", "cash_sessions.index", "cash_movements.index", "cash_summary.index"],
        "cash_registers.store" => ["cash_registers.index"],
        "cash_sessions.list" => ["cash_sessions.index"],
        "cash_sessions.open" => ["cash_sessions.index", "cash_registers.index"],
        "cash_sessions.close" => ["cash_sessions.index", "cash_registers.index"],
        "cash_movements.list" => ["cash_movements.index"],
        "cash_movements.store" => ["cash_movements.index"],
        "cash_movements.export" => ["cash_movements.index"],
        "cash_summary.data" => ["cash_summary.index"],
    ],
];
